### ISSUE TITLE
Sizing

### ISSUE THREAD

**Issue by kingsleyh** [pablohirafuji/elm-qrcode#3]
Hi

Is there any way to get QR codes to be all of the same size? currently I have 2 on the page and 1 is much bigger than the other - would be nice if they were both the same size from a visual perspective

**Comment by pablohirafuji** [comment]
Hey

If you can use the `toSvg` render version, you can define the absolute size of the QR Codes via CSS, defining the `width` of the SGV element to the desired width.

In the future I plan to add that option to the canvas rendering. I didn't do that yet because I am thinking in a nice API for the possibility of defining either the absolute size or the module (each square that composes the QR Code) size.

**Comment by kingsleyh** [comment]
Ah ok - awesome thanks :)

**Comment by pablohirafuji** [comment]
Canvas sizing available in 2.2.0 :)

**Comment by kingsleyh** [comment]
Awesome!! Thanks a lot - that's great!
